### ISSUE TITLE
config page

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#1]
Formatting:
- spid logo

Metadata-impacting settings:
- OrganizationName, OrganizationDisplayName, OrganizationURL
- gli attributi che ci vogliamo far dare: elenco degli attributi standard SPID con checkbox attiva / disattiva
- bottone "Configura plugin", vedi #22

spiegare all'utente che se cambia uno di questi 2 settaggi **deve ridistribuire il metadata del SP a tutti gli IdP**, dal metadata link (attualmente http://localhost:8099/wp-login.php?sso=spid&metadata che tra l'altro è bruttino)

WP Plugin config:
- SPID level (1 or 2)
- IdP selection: checkbox to activate / deactivate available IdPs (dai files presenti in idp_metadata)
- what WP role the new user should be assigned to (i.e. Subscriber)

**Comment by Valamiro** [comment]
https://balsamiq.cloud/s4w5g7z/p2rvfa7

**Comment by simevo** [comment]
![tab1_configurazione_0](https://user-images.githubusercontent.com/8254819/47546196-6ac75880-d8f0-11e8-86de-83b5e0f173c0.png)
![tab2_metadata](https://user-images.githubusercontent.com/8254819/47546201-70bd3980-d8f0-11e8-9a0b-07dbc3979443.png)
![tab3_button](https://user-images.githubusercontent.com/8254819/47546206-77e44780-d8f0-11e8-97ce-076d8e8c9139.png)
![tab4_certificati_0](https://user-images.githubusercontent.com/8254819/47546300-e88b6400-d8f0-11e8-8a48-fb9fac8d3619.png)
![tab6_aiuto](https://user-images.githubusercontent.com/8254819/47546337-12dd2180-d8f1-11e8-9018-5045fff04ef9.png)

**Comment by michaeltieso** [comment]
I'll work on this a bit today after lunch

**Comment by simevo** [comment]
OK ! please have a look at https://github.com/simevo/spid-wordpress/tree/feature/issue-1-configPage and get in touch with @Valamiro
