### ISSUE TITLE
implement logout

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#12]
if you log onto WP with this plugin then logout, the SPID session will stay open

trying to login again breaks it !

we should call `$this->auth->logout()`

**Comment by simevo** [comment]
FTMB, you can "manually" logout from SPID by clearing the cookies in chrome inspector

**Comment by giuliogatto** [comment]
I have noticed that too, this is also related to : https://github.com/simevo/spid-wordpress/issues/5
I am now trying to find a way to keep the the 2 sessions (global and invididual) synchronized

**Comment by simevo** [comment]
https://spid-regole-tecniche.readthedocs.io/en/latest/single-logout.html

**Comment by simevo** [comment]
My plan is to hook into the [`wp_logout`](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_logout) action hook and invoke [`Italia\Spid\Sp::logout`](https://github.com/italia/spid-php-lib#performing-logout)

Currently before logging in with SPID I have two cookies: `PHPSESSID` and `wordpress_test_cookie`
After logging in with SPID I have 4 more: `session` and 3 some `wordpress_xxx`
After logging out I have three: `PHPSESSID`, `wordpress_test_cookie` and `session`
