### ISSUE TITLE
returning SPID user cannot log in

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#13]
when a SPID used logs to WP for the 1st time, a WP user is created; if this user logs out (beware #12 !) then tries to login again she gets "Questo nome utente esiste già!" (this username already exists):

![image](https://user-images.githubusercontent.com/8254819/47090006-4699b680-d222-11e8-88f1-4743fe8cbe0e.png)

**Comment by michaeltieso** [comment]
How do you plan on working on this one?

**Comment by simevo** [comment]
There must be something wrong here: https://github.com/simevo/spid-wordpress/blame/master/includes/class-spid-core.php#L128
I'd like to give it a try this afternoon. Any suggestions you migh have are welcome !
