### ISSUE TITLE
show display link to plugin's settings page in plugin list

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#27]
as in:

![screenshot_20181022_092942](https://user-images.githubusercontent.com/8254819/47281910-70b1f680-d5dd-11e8-88bc-51675ed7e08d.png)

**Comment by michaeltieso** [comment]
https://github.com/simevo/spid-wordpress/commit/23eddeb9d8182dc76f900948bb37f6c5288559e8
