### ISSUE TITLE
exclude certain files from the distributables

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#29]
when we will tag a release, github will make zip and tar.gz downloads available [under releases](https://github.com/simevo/spid-wordpress/releases)

we do not want ship certain files with those distributables, for example `composer.json` and `composer.lock` which are meaningless to people not involved in the plugin development

within spid-php-lib we have successfully used the [.gitattributes file](https://github.com/italia/spid-php-lib/blob/master/.gitattributes) to achieve that effect

**Comment by michaeltieso** [comment]
Good idea!
