### ISSUE TITLE
guest access (optional)

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#3]
to be evaluated: should we allow a user to access "anonymously" WP without any SPID user attributes ?

this could be used to allow controlled access to read-only, non user-specific data

a generic WP user "guest" could be used for all logins

**Comment by giuliogatto** [comment]
At the moment we are forcing at least 2 attributes (spidCode and email) for the level 1 authentication. The idea sounded interesting in the beginning, but the more I think about it the more I am convinced that letting a user access some content anonymously doesn't offer any advantage. Maybe we should try and think of an actual example of real implementation first

**Comment by simevo** [comment]
I agree ! wontfix
