### ISSUE TITLE
Moving external files to the plugin

### ISSUE THREAD

**Issue by michaeltieso** [simevo/spid-wordpress#38]
https://github.com/simevo/spid-wordpress/blob/c81bf4c563ba61b368cad9bdde763b7a8f756b2a/includes/class-spid-core.php#L200-L215

Should these external scripts be loaded internally? I worry that changes to `spid-button.min.js` may break functionality in the future for the plugin or if the location of the file moves. We can push an update to the plugin but we all know people may take awhile to update. `spid-smart-button` looks like it's still in early development and doesn't appear to be versioned yet too. Thoughts?

**Comment by simevo** [comment]
the mid-term plan is to deliver the spid-button over a CDN
