### ISSUE TITLE
composer install fails on PHP 7.0

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#42]
while setting up travis (#39) I stumbled upon this https://travis-ci.com/simevo/spid-wordpress/jobs/153619905

```
$ composer install --no-interaction
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 2
    - Installation request for myclabs/deep-copy 1.8.1 -> satisfiable by myclabs/deep-copy[1.8.1].
    - myclabs/deep-copy 1.8.1 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 3
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 5.0.10 requires doctrine/instantiator ^1.0.5 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpunit/phpunit-mock-objects 5.0.10 -> satisfiable by phpunit/phpunit-mock-objects[5.0.10].
```

**Comment by michaeltieso** [comment]
Is this still showing up as an issue for you?

**Comment by simevo** [comment]
since you merged PR #43  it's now reported by Travis for master as well:
https://travis-ci.com/simevo/spid-wordpress/jobs/153789100

**Comment by simevo** [comment]
this happens when one performs `composer require ..` or `composer update` on a system which runs PHP 7.1 or later, and then commits the `composer.lock` file; I normally use a container with debian stretch (our standard development environment) to run these commands, them commit the resulting `composer.lock`

**Comment by michaeltieso** [comment]
I see. Why is Travis being used for this? This is only for development, not pushing to live. Your PHP version is irreverent for building.
