### ISSUE TITLE
SPID users should only be allowed to login with SPID

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#58]
A user may gain access to a WP install once with her SPID login, then loose access / change her SPID login.
After a year, by resetting her WP password she could login with a regular WordPress user/pass, bypassing SPID, and her SPID attributes would not be refreshed (see #57).

To avoid these situations, on login with regular WP user/pass, if the user is detected as a SPID user (has a spidCode in metadata), we need to force SPID login !

**Comment by simevo** [comment]
Interesting topic ! During a SPID login, the user is asked for confirmation before getting the data:
![image](https://user-images.githubusercontent.com/8254819/47654591-6b2f5000-db8b-11e8-93cd-d6b3d4014f0b.png)

This fulfills just the first of the GDPR requirements (informed consent). The other requirements (show data / delete data on request, notify breeches ...) are still on the service provider shoulders. We as SPID authenticaton plugin devs cannot solve all these ... I know there are some other WP plugins that can help.

BTW I found a few mentions of the impacts of GDPR on SPID here:
https://forum.italia.it/t/convenzione-spid-dove-trovarla/1456/6
https://forum.italia.it/t/delega-completa-per-identita-spid/3460/4

**Comment by giuliogatto** [comment]
This is potentially VERY dangerous: if the plugin collects and saves data automatically from the IDP, and the Service Provider doesn't implement the right GDPR policies, then the plugin exposes the SP to legal risks.
I suggest  not save to anything SPID user related on the framework/CMS database. 
Some CMS are very well known for security issues, their source code is public and these plugins code is public, too.

**Comment by giuliogatto** [comment]
As an alternative solution: we need to make it clear in a Disclaimer within the repo that whoever install the plugin is responsible for all GDPR policies implementations. The fact that the plugin saves some sensible information in the host framework/CMS database must be acknowledged.
