### ISSUE TITLE
GDPR warnings

### ISSUE THREAD

**Issue by simevo** [simevo/spid-wordpress#64]
write in clear letters that if the plugin user chooses to store user data in WP, she is bound by the GDPR to take care of these data, respond to user requests for access and deletion, and reporting breeches

**Comment by simevo** [comment]
I propose to put it:
1. in the README
2. in the main admin screen
3. in the config page where the admin selects the attributes to get from SPID

**Comment by michaeltieso** [comment]
I can do with 2 and 3 but will need help with the wording. Let me know what to put and I'll take care of this quickly.

**Comment by simevo** [comment]
OK ! I'll take care of the README !

Draft texts:

- 2 (in the main admin screen)

> Quando il plugin è attivo, in base alle <a href="/wp-admin/admin.php?page=spid_opzioni&action=metadata">impostazioni sugli attributi utente</a>, esso può salvare "dati personali" degli utenti SPID nel database WordPress. Il plugin acquisisce il "valido consenso" ai sensi della GDPR (Regolamento generale sulla protezione dei dati, in inglese General Data Protection Regulation), tuttavia restano in carico al Service Provider: la sicurezza dell'installazione WordPress, la gestione delle richieste da parte degli utenti di accesso e cancellazione dei dati, e la notifica delle violazioni dei dati.

- 3 (in the config page, Tab 2: Metadata where the admin selects the attributes to get from SPID i.e. "Seleziona gli attributi utente")

> Selezionando uno o più attributi utente, oltre agli attributi strettamente necessari al funzionamento del plugin (codice identificativo SPID e indirizzo di posta elettronica), aumentano i rischi e la complessità della gestione di questi dati "personali" dal punto di vista della GDPR. Si rimanda al disclaimer riportato nella <a href="/wp-admin/index.php">Dashboard</a>.

@giuliogatto what do you think ?

**Comment by giuliogatto** [comment]
Mi sembra ok, aggiungerei: "e la pubblicazione dell'informativa per gli utenti su fini e modalità del trattamento dei dati personali. ", come di seguito:

> Quando il plugin è attivo, in base alle <a href="/wp-admin/admin.php?page=spid_opzioni&action=metadata">impostazioni sugli attributi utente</a>, esso può salvare "dati personali" degli utenti SPID nel database WordPress. Il plugin acquisisce il "valido consenso" ai sensi della GDPR (Regolamento generale sulla protezione dei dati, in inglese General Data Protection Regulation), tuttavia restano in carico al Service Provider: la sicurezza dell'installazione WordPress, la gestione delle richieste da parte degli utenti di accesso e cancellazione dei dati,  la notifica delle violazioni dei dati e la pubblicazione dell'informativa per gli utenti su fini e modalità del trattamento dei dati personali.
